import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pete Estates</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <main>
        <section className="bg-blue-700">
          <h1 className="text-3xl font-bold underline flex justify-center">
            Hello world!
          </h1>
        </section>
      </main>
    </div>
  )
}
